import type {Locale} from "./i18n";
const en={back:"Back to the Companion",eyebrow:"GTA VI COMPANION / ORIGINAL 3D ARCADE",title:"NEON GETAWAY.",intro:"An original 3D car-heist game in a fictional neon district. Find three rare cars, weave through moving traffic and deliver each one to the garage.",start:"Start the run",restart:"Try again",goal:"THREE CARS. ONE NIGHT.",mission:"Pick a character color, then take the streets.",win:"All cars delivered",lose:"The run is over",finalScore:"Final score",contract:"ACTIVE CONTRACT",contractText:"Find the original supercar and get close enough to enter.",find:"Find the car",enter:"Press E to enter",escape:"Drive to",garage:"THE CYAN GARAGE",heat:"Hits",move:"WASD / arrows move and drive · E enters or exits · Shift sprints on foot · Space brakes · R restarts",character:"Character color",leaderboard:"Local leaderboard",localBoard:"Saved on this device only. Scores are not globally verified.",noScores:"Your first run can claim the top spot.",alias:"Player name",save:"Save score",sound:"Sound",action:"Enter / exit",demoNote:"Public practice run. The full arcade is a Pro feature. This is an independent original fan game, not GTA VI gameplay.",fanNote:"Independent original fan game. Vehicle designs and city are fictional; this is not GTA VI gameplay.",community:"Join the community"};
type Copy=typeof en;
const pt:Copy={back:"Voltar ao Companion",eyebrow:"GTA VI COMPANION / ARCADE 3D ORIGINAL",title:"FUGA NEON.",intro:"Um jogo 3D original de roubo de carros em um bairro fictício. Encontre três carros raros, desvie do trânsito e leve cada um à garagem.",start:"Começar a fuga",restart:"Tentar de novo",goal:"TRÊS CARROS. UMA NOITE.",mission:"Escolha a cor do personagem e entre nas ruas.",win:"Todos os carros entregues",lose:"A fuga acabou",finalScore:"Pontuação final",contract:"CONTRATO ATIVO",contractText:"Encontre o supercarro original e aproxime-se para entrar.",find:"Encontre o carro",enter:"Pressione E para entrar",escape:"Dirija até",garage:"A GARAGEM CIANO",heat:"Colisões",move:"WASD / setas movem e dirigem · E entra ou sai · Shift corre a pé · Espaço freia · R reinicia",character:"Cor do personagem",leaderboard:"Ranking local",localBoard:"Salvo apenas neste dispositivo. Pontuações não são verificadas globalmente.",noScores:"Sua primeira fuga pode ficar em primeiro.",alias:"Nome do jogador",save:"Salvar pontos",sound:"Som",action:"Entrar / sair",demoNote:"Treino público. O arcade completo é um recurso Pro. Este é um jogo autoral, não é gameplay de GTA VI.",fanNote:"Jogo independente e autoral. Carros e cidade são fictícios; não é gameplay de GTA VI.",community:"Entre na comunidade"};
const es:Copy={back:"Volver al Companion",eyebrow:"GTA VI COMPANION / ARCADE 3D ORIGINAL",title:"FUGA NEÓN.",intro:"Un juego 3D original de robo de coches en un barrio ficticio. Encuentra tres coches raros, esquiva el tráfico y lleva cada uno al garaje.",start:"Empezar la fuga",restart:"Intentarlo de nuevo",goal:"TRES COCHES. UNA NOCHE.",mission:"Elige el color del personaje y sal a la calle.",win:"Todos los coches entregados",lose:"La fuga terminó",finalScore:"Puntuación final",contract:"CONTRATO ACTIVO",contractText:"Encuentra el supercoche original y acércate para entrar.",find:"Encuentra el coche",enter:"Pulsa E para entrar",escape:"Conduce hasta",garage:"EL GARAJE CIAN",heat:"Choques",move:"WASD / flechas mueven y conducen · E entra o sale · Shift corre a pie · Espacio frena · R reinicia",character:"Color del personaje",leaderboard:"Clasificación local",localBoard:"Guardada solo en este dispositivo. Puntuaciones sin verificación global.",noScores:"Tu primera fuga puede liderar la tabla.",alias:"Nombre del jugador",save:"Guardar puntos",sound:"Sonido",action:"Entrar / salir",demoNote:"Práctica pública. El arcade completo es Pro. Juego original, no es gameplay de GTA VI.",fanNote:"Juego independiente y original. Coches y ciudad ficticios; no es gameplay de GTA VI.",community:"Únete a la comunidad"};
const nl:Copy={back:"Terug naar Companion",eyebrow:"GTA VI COMPANION / ORIGINELE 3D-ARCADE",title:"NEONONTSNAPPING.",intro:"Een originele 3D-autoroof in een fictieve neonwijk. Zoek drie zeldzame auto's, ontwijk het verkeer en breng ze naar de garage.",start:"Start de rit",restart:"Probeer opnieuw",goal:"DRIE AUTO'S. ÉÉN NACHT.",mission:"Kies een personagekleur en ga de straat op.",win:"Alle auto's afgeleverd",lose:"De rit is voorbij",finalScore:"Eindscore",contract:"ACTIEVE OPDRACHT",contractText:"Zoek de originele superauto en kom dichtbij om in te stappen.",find:"Zoek de auto",enter:"Druk op E om in te stappen",escape:"Rijd naar",garage:"DE CYAAN GARAGE",heat:"Botsingen",move:"WASD / pijltjes bewegen en sturen · E in- of uitstappen · Shift sprint · Spatie remt · R herstart",character:"Personagekleur",leaderboard:"Lokaal klassement",localBoard:"Alleen op dit apparaat opgeslagen. Scores zijn niet wereldwijd geverifieerd.",noScores:"Jouw eerste rit kan bovenaan komen.",alias:"Spelersnaam",save:"Score opslaan",sound:"Geluid",action:"In- / uitstappen",demoNote:"Openbare oefenronde. De volledige arcade is Pro. Origineel spel, geen GTA VI-gameplay.",fanNote:"Onafhankelijk origineel fanspel. Auto's en stad zijn fictief; geen GTA VI-gameplay.",community:"Ga naar de community"};
export const arcadeCopy:Record<Locale,Copy & {demoBoard:string;unlockPro:string;demoGoal:string;demoIntro:string}>={
 en:{...en,demoBoard:"Play one contract free. The three-car run and local records unlock with Pro.",unlockPro:"Unlock the full run",demoGoal:"ONE CAR. ONE NIGHT.",demoIntro:"Play one free car-heist contract in our original 3D neon district. Find the car, weave through traffic and reach the garage."},
 es:{...es,demoBoard:"Juega un contrato gratis. La fuga de tres coches y el ranking local son Pro.",unlockPro:"Desbloquear la fuga completa",demoGoal:"UN COCHE. UNA NOCHE.",demoIntro:"Juega gratis un contrato 3D original. Encuentra el coche, esquiva el tráfico y llega al garaje."},
 "pt-BR":{...pt,demoBoard:"Jogue um contrato grátis. A fuga com três carros e o ranking local são Pro.",unlockPro:"Desbloquear a fuga completa",demoGoal:"UM CARRO. UMA NOITE.",demoIntro:"Jogue grátis um contrato 3D original. Encontre o carro, desvie do trânsito e chegue à garagem."},
 nl:{...nl,demoBoard:"Speel één opdracht gratis. De rit met drie auto's en lokale scores zijn Pro.",unlockPro:"Ontgrendel de volledige rit",demoGoal:"ÉÉN AUTO. ÉÉN NACHT.",demoIntro:"Speel gratis één originele 3D-opdracht. Zoek de auto, ontwijk het verkeer en bereik de garage."}
};

