import type { Locale } from "./i18n";

export const editorialCopy: Record<Locale, {
  news: string; newsIntro: string; latest: string; source: string; all: string; community: string;
  music: string; musicTitle: string; musicText: string; musicLink: string; musicNote: string;
  buy: string; buyIntro: string; buyNotice: string; buyCta: string; back: string; plans: string;
  rockstar: string; playstation: string; xbox: string;
}> = {
  en: { news:"Official news",newsIntro:"The latest confirmed GTA VI updates, selected from Rockstar Games. Open each source for full details.",latest:"Selected 29 Sep 2026",source:"Read at Rockstar",all:"All Rockstar updates",community:"Discuss in the community",music:"THE MUSIC",musicTitle:"Hear what is confirmed.",musicText:"Rockstar has announced Grand Theft Auto VI: The Album. The game's radio stations have not yet been revealed, so we won't present invented stations as official.",musicLink:"Explore the official album announcement",musicNote:"Music opens on Rockstar; no unlicensed tracks are hosted here.",buy:"Buy GTA VI",buyIntro:"Choose your console and complete your pre-order directly with an official store.",buyNotice:"GTA VI Companion does not sell or deliver the game. Edition, price and availability depend on your region and the store you choose.",buyCta:"Go to store",back:"Back to GTA VI Companion",plans:"Companion Pro plans",rockstar:"Rockstar Store",playstation:"PlayStation Store · PS5",xbox:"Xbox Store · Series X|S" },
  es: { news:"Noticias oficiales",newsIntro:"Las últimas novedades confirmadas de GTA VI, seleccionadas de Rockstar Games. Abre cada fuente para los detalles.",latest:"Selección del 29 sep 2026",source:"Leer en Rockstar",all:"Todas las noticias de Rockstar",community:"Debatir en la comunidad",music:"LA MÚSICA",musicTitle:"Escucha lo confirmado.",musicText:"Rockstar ha anunciado Grand Theft Auto VI: The Album. Todavía no ha revelado las emisoras del juego; no presentaremos emisoras inventadas como oficiales.",musicLink:"Ver el anuncio oficial del álbum",musicNote:"La música se abre en Rockstar; aquí no alojamos canciones sin licencia.",buy:"Comprar GTA VI",buyIntro:"Elige tu consola y completa la reserva directamente en una tienda oficial.",buyNotice:"GTA VI Companion no vende ni entrega el juego. Edición, precio y disponibilidad dependen de tu región y de la tienda elegida.",buyCta:"Ir a la tienda",back:"Volver a GTA VI Companion",plans:"Planes Companion Pro",rockstar:"Rockstar Store",playstation:"PlayStation Store · PS5",xbox:"Xbox Store · Series X|S" },
  "pt-BR": { news:"Notícias oficiais",newsIntro:"As novidades confirmadas de GTA VI, selecionadas da Rockstar Games. Abra a fonte para ver todos os detalhes.",latest:"Seleção de 29 set 2026",source:"Ler na Rockstar",all:"Todas as notícias da Rockstar",community:"Debater na comunidade",music:"A MÚSICA",musicTitle:"Ouça o que foi confirmado.",musicText:"A Rockstar anunciou Grand Theft Auto VI: The Album. As estações de rádio do jogo ainda não foram reveladas; não apresentaremos estações inventadas como oficiais.",musicLink:"Ver o anúncio oficial do álbum",musicNote:"A música abre na Rockstar; não hospedamos faixas sem licença aqui.",buy:"Comprar GTA VI",buyIntro:"Escolha o console e conclua a pré-venda diretamente em uma loja oficial.",buyNotice:"GTA VI Companion não vende nem entrega o jogo. Edição, preço e disponibilidade dependem da sua região e da loja escolhida.",buyCta:"Ir para a loja",back:"Voltar ao GTA VI Companion",plans:"Planos Companion Pro",rockstar:"Rockstar Store",playstation:"PlayStation Store · PS5",xbox:"Xbox Store · Series X|S" },
  nl: { news:"Officieel nieuws",newsIntro:"De recentste bevestigde GTA VI-updates, geselecteerd van Rockstar Games. Open de bron voor alle details.",latest:"Selectie van 29 sep 2026",source:"Lees bij Rockstar",all:"Alle Rockstar-updates",community:"Bespreek in de gemeenschap",music:"DE MUZIEK",musicTitle:"Luister naar wat bevestigd is.",musicText:"Rockstar heeft Grand Theft Auto VI: The Album aangekondigd. De radiozenders in het spel zijn nog niet bekendgemaakt; we presenteren geen verzonnen zenders als officieel.",musicLink:"Bekijk de officiële album-aankondiging",musicNote:"Muziek opent bij Rockstar; we hosten hier geen nummers zonder licentie.",buy:"Koop GTA VI",buyIntro:"Kies je console en rond de voorbestelling rechtstreeks af bij een officiële winkel.",buyNotice:"GTA VI Companion verkoopt of levert het spel niet. Editie, prijs en beschikbaarheid hangen af van je regio en de gekozen winkel.",buyCta:"Naar de winkel",back:"Terug naar GTA VI Companion",plans:"Companion Pro-abonnementen",rockstar:"Rockstar Store",playstation:"PlayStation Store · PS5",xbox:"Xbox Store · Series X|S" }
};

export const officialNews = [
  { date:"2026-09-17",title:"Grand Theft Auto VI: The Album",href:"https://www.rockstargames.com/newswire/article/7599a881942544/announcing-grand-theft-auto-vi-the-album-coming-november-19",tag:"MUSIC" },
  { date:"2026-08-27",title:"Grand Theft Auto VI: An Extended Look",href:"https://www.rockstargames.com/VI/an-extended-look",tag:"VIDEO" },
  { date:"2026-06-24",title:"Pre-Order Grand Theft Auto VI",href:"https://www.rockstargames.com/newswire/article/5171972o3ak5oa/pre-order-grand-theft-auto-vi-on-june-25",tag:"PRE-ORDER" },
] as const;

export const officialStores = [
  { key:"rockstar",href:"https://store.rockstargames.com/game/buy-gta-vi",detail:"PS5 / Xbox Series X|S" },
  { key:"playstation",href:"https://store.playstation.com/concept/10000730",detail:"PlayStation 5" },
  { key:"xbox",href:"https://www.xbox.com/en-us/games/store/grand-theft-auto-vi/9nl3wwnzlzzn",detail:"Xbox Series X|S" },
] as const;
