import type { Locale } from "./i18n";
const en={eyebrow:"THE FIELD GUIDE",title:"THE WORLD IS THE STORY.",intro:"Six systems to investigate. Every note separates a research question from our own prototype, so fan speculation stays clear.",question:"What to investigate",prototype:"Original community exercise",source:"Follow primary sources",back:"Back to Companion",community:"Explore evidence board",topics:[
{title:"Reputation & consequences",question:"What can the official footage actually tell us about attention, witnesses and consequences? A trailer scene does not establish persistent memory.",prototype:"Write a consequence scenario: who saw it, what changed and how can trust be rebuilt?"},
{title:"People & daily routines",question:"Look for repeated behavior in distinct scenes. A glimpse of a crowd cannot confirm complete schedules or persistent NPC lives.",prototype:"Draft a resident with a destination, routine and reason to react."},
{title:"Body & appearance",question:"Separate visible variety from confirmed playable rules. A costume does not prove muscle, fatigue or body-stat simulation.",prototype:"Plan a character dossier with habits, visual references and milestones."},
{title:"Economy & restoration",question:"Ask what work costs, what rewards it creates and what sinks would keep an economy useful. Use verified numbers only when available.",prototype:"Estimate a fictional vehicle restoration budget and work needed to reach it."},
{title:"Characters & relationships",question:"Keep official characters separate from unconfirmed switching, co-op and relationship mechanics.",prototype:"Write two dossiers with distinct motives, then plan a scene that tests their shared goal."},
{title:"Social stories & photography",question:"Do official materials show a player-facing publishing feature, or just social visuals in the world? The distinction matters.",prototype:"Create a trailer observation with source, timestamp and spoiler label for the evidence board."}]};
type Copy=typeof en;
const pt:Copy={eyebrow:"GUIA DE CAMPO",title:"O MUNDO É A HISTÓRIA.",intro:"Seis sistemas para investigar. Cada nota separa uma pergunta de pesquisa de um exercício nosso, para deixar clara a especulação dos fãs.",question:"O que investigar",prototype:"Exercício original da comunidade",source:"Consulte fontes primárias",back:"Voltar ao Companion",community:"Explorar o quadro de evidências",topics:[
{title:"Reputação e consequências",question:"O que o material oficial realmente mostra sobre atenção, testemunhas e consequências? Uma cena do trailer não comprova memória persistente.",prototype:"Escreva um cenário: quem viu, o que mudou e como recuperar a confiança?"},
{title:"Pessoas e rotinas",question:"Procure comportamentos repetidos em cenas diferentes. Um vislumbre de multidão não confirma rotinas completas dos personagens.",prototype:"Crie um morador com destino, rotina e motivo para reagir."},
{title:"Corpo e aparência",question:"Separe variedade visual de regras jogáveis confirmadas. Uma roupa não prova simulação de músculos, fadiga ou atributos corporais.",prototype:"Planeje um dossiê de personagem com hábitos, referências visuais e marcos."},
{title:"Economia e restauração",question:"Pergunte quanto custa o trabalho, que recompensa ele traz e o que mantém uma economia útil. Use números verificados quando existirem.",prototype:"Estime um orçamento fictício para restaurar um veículo e o trabalho necessário."},
{title:"Personagens e relações",question:"Separe personagens oficiais de mecânicas não confirmadas de troca, cooperação e relacionamento.",prototype:"Escreva dois dossiês com motivações distintas e planeje uma cena que teste o objetivo comum."},
{title:"Histórias sociais e fotografia",question:"O material oficial mostra uma função de publicação para jogadores ou apenas imagens sociais no mundo? A distinção importa.",prototype:"Crie uma observação do trailer com fonte, horário e aviso de spoiler para o quadro de evidências."}]};
const es:Copy={eyebrow:"GUÍA DE CAMPO",title:"EL MUNDO ES LA HISTORIA.",intro:"Seis sistemas por investigar. Cada nota distingue una pregunta de investigación de un ejercicio propio, para que la especulación de los fans quede clara.",question:"Qué investigar",prototype:"Ejercicio original de la comunidad",source:"Consulta fuentes primarias",back:"Volver al Companion",community:"Explorar el tablón de pruebas",topics:[
{title:"Reputación y consecuencias",question:"¿Qué muestra realmente el material oficial sobre testigos y consecuencias? Una escena del tráiler no demuestra memoria persistente.",prototype:"Escribe un escenario: ¿quién lo vio, qué cambió y cómo se recupera la confianza?"},
{title:"Personas y rutinas",question:"Busca comportamientos repetidos en escenas distintas. Una multitud no confirma rutinas completas de los personajes.",prototype:"Crea un residente con destino, rutina y motivo para reaccionar."},
{title:"Cuerpo y apariencia",question:"Distingue variedad visual de reglas jugables confirmadas. Un atuendo no prueba simulación de músculos, cansancio o atributos corporales.",prototype:"Planea un expediente de personaje con hábitos, referencias y metas."},
{title:"Economía y restauración",question:"Pregunta cuánto cuesta el trabajo, qué recompensa aporta y qué mantiene útil una economía. Usa cifras verificadas cuando existan.",prototype:"Estima un presupuesto ficticio para restaurar un vehículo y el trabajo necesario."},
{title:"Personajes y relaciones",question:"Distingue personajes oficiales de mecánicas no confirmadas de cambio, cooperación y relaciones.",prototype:"Escribe dos expedientes con motivos distintos y planea una escena que ponga a prueba su objetivo común."},
{title:"Historias sociales y fotografía",question:"¿El material oficial muestra una función para publicar o solo imágenes sociales del mundo? La diferencia importa.",prototype:"Crea una observación del tráiler con fuente, momento y aviso de spoilers para el tablón de pruebas."}]};
const nl:Copy={eyebrow:"VELDGIDS",title:"DE WERELD IS HET VERHAAL.",intro:"Zes systemen om te onderzoeken. Elke notitie scheidt een onderzoeksvraag van ons eigen prototype, zodat speculatie duidelijk blijft.",question:"Wat te onderzoeken",prototype:"Originele gemeenschapsopdracht",source:"Bekijk primaire bronnen",back:"Terug naar Companion",community:"Verken het bewijsbord",topics:[
{title:"Reputatie en gevolgen",question:"Wat laat officieel materiaal werkelijk zien over aandacht, getuigen en gevolgen? Een trailerscène bewijst geen blijvend geheugen.",prototype:"Schrijf een scenario: wie zag wat, wat veranderde en hoe kan vertrouwen terugkomen?"},
{title:"Mensen en dagelijkse routines",question:"Zoek herhaald gedrag in verschillende scènes. Een menigte bevestigt geen complete dagschema's van personages.",prototype:"Bedenk een bewoner met een bestemming, routine en reden om te reageren."},
{title:"Lichaam en uiterlijk",question:"Maak onderscheid tussen zichtbare variatie en bevestigde spelregels. Een outfit bewijst geen simulatie van spieren, vermoeidheid of lichaamsstatistieken.",prototype:"Maak een personagedossier met gewoontes, beeldreferenties en mijlpalen."},
{title:"Economie en restauratie",question:"Vraag wat werk kost, wat het oplevert en welke uitgaven een economie zinvol houden. Gebruik alleen geverifieerde cijfers.",prototype:"Schat de kosten van een fictieve voertuigrestauratie en het benodigde werk."},
{title:"Personages en relaties",question:"Houd officiële personages gescheiden van onbevestigde mechanismen voor wisselen, samenspelen en relaties.",prototype:"Schrijf twee dossiers met verschillende motieven en plan een scène die hun gedeelde doel test."},
{title:"Sociale verhalen en fotografie",question:"Tonen officiële beelden een functie waarmee spelers publiceren, of alleen sociale beelden in de spelwereld? Dat verschil telt.",prototype:"Maak een trailerobservatie met bron, tijdstip en spoilerlabel voor het bewijsbord."}]};
export const guideCopy:Record<Locale,Copy>={en,es,"pt-BR":pt,nl};
