"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Gauge, Users, Route, Save } from "lucide-react";
import { browserLocale,isLocale,type Locale } from "@/lib/i18n";
import { labCopy } from "@/lib/lab-copy";
import { simulate,type Scenario } from "@/lib/lab-model";
const initial:Scenario={crew:2,heat:35,route:"coast"};
function valid(value:unknown):value is Scenario { if(!value||typeof value!=="object")return false;const v=value as Record<string,unknown>;return Number.isInteger(v.crew)&&Number(v.crew)>=1&&Number(v.crew)<=4&&Number.isInteger(v.heat)&&Number(v.heat)>=0&&Number(v.heat)<=100&&["quiet","coast","downtown"].includes(String(v.route)); }
export default function CreatorLab({userId}:{userId:string}){const [locale,setLocale]=useState<Locale>("en"),[scenario,setScenario]=useState<Scenario>(initial),[saved,setSaved]=useState<Scenario|null>(null),[notice,setNotice]=useState(false);const t=labCopy[locale],result=simulate(scenario),storageKey=`vi-creator-lab:${userId}`;
useEffect(()=>{let l=browserLocale(navigator.language);try{const choice=localStorage.getItem("vi-language");if(isLocale(choice))l=choice;const raw=localStorage.getItem(storageKey);if(raw){const parsed:unknown=JSON.parse(raw);if(valid(parsed))setSaved(parsed);}}catch{}setLocale(l);},[storageKey]);
const update=(next:Scenario)=>{setScenario(next);setNotice(false);};
const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(scenario));setSaved(scenario);setNotice(true);}catch{setNotice(false);}};
return <div className="lab-page"><header><Link href="/"><ArrowLeft size={16}/>{t.back}</Link><select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="en">English</option><option value="es">Español</option><option value="pt-BR">Português (BR)</option></select></header><main><span className="merged-kicker">{t.eyebrow}</span><h1>{t.title}</h1><p className="lab-intro">{t.intro}</p><div className="lab-stage"><section className="lab-controls"><div className="lab-control-head"><Users size={23}/><label htmlFor="lab-crew">{t.crew}<strong>{scenario.crew} {t.members}</strong></label></div><input id="lab-crew" type="range" min="1" max="4" value={scenario.crew} onChange={e=>update({...scenario,crew:Number(e.target.value)})}/><div className="lab-control-head"><Gauge size={23}/><label htmlFor="lab-heat">{t.heat}<strong>{scenario.heat}%</strong></label></div><input id="lab-heat" type="range" min="0" max="100" step="5" value={scenario.heat} onChange={e=>update({...scenario,heat:Number(e.target.value)})}/><div className="lab-control-head"><Route size={23}/><span>{t.route}</span></div><div className="lab-routes">{(["quiet","coast","downtown"] as const).map(route=><button key={route} type="button" aria-pressed={scenario.route===route} onClick={()=>update({...scenario,route})}>{t[route]}</button>)}</div></section><section className="lab-outlook" aria-live="polite"><span className="merged-kicker">{t.plan}</span><div className="lab-orbit" style={{"--chance":`${result.chance}%`} as React.CSSProperties}><div><strong>{result.chance}%</strong><span>{t.chance}</span></div></div><div className="lab-metrics"><div><span>{t.payout}</span><strong>${result.payout.toLocaleString(locale)}</strong></div><div><span>{t.minutes}</span><strong>{result.minutes}</strong></div></div><p>{scenario.heat<34?t.low:scenario.heat<70?t.medium:t.high}</p></section></div><div className="lab-footer"><p>{t.note}</p><div><button type="button" onClick={()=>update(initial)}>{t.reset}</button><button type="button" onClick={save}><Save size={16}/>{t.save}</button></div></div>{notice&&<p className="lab-saved" role="status">{t.saved}</p>}{saved&&<p className="lab-previous">{t.previous}: {t[saved.route]} · {saved.crew} {t.members} · {saved.heat}%</p>}<Link className="lab-community" href={`/community?lang=${locale}`}>COMMUNITY <ArrowUpRight size={16}/></Link></main></div>;
}
