import Link from "next/link";
import { ArrowLeft, ArrowUpRight, ShieldCheck, LockKeyhole } from "lucide-react";
import { authClient } from "@/lib/auth/server";
import { hasActiveSubscription } from "@/lib/auth/policy";
import { communityCopy } from "@/lib/community-copy";
import type { Locale } from "@/lib/i18n";
import { createPost, reportPost, votePost } from "./actions";
import "./community.css";
export const dynamic="force-dynamic";
type Post={id:string;author_name:string;kind:"observation"|"theory"|"crew";title:string;body:string;source_url:string|null;source_time:number|null;platform:string|null;language:string|null;spoiler:boolean;created_at:string;community_votes?:{count:number}[]};
export default async function Community({searchParams}:{searchParams:Promise<{kind?:string;lang?:string;error?:string}>}){
  const query=await searchParams;
  const locale:Locale=query.lang==="es"?"es":query.lang==="pt-BR"?"pt-BR":"en";
  const t=communityCopy[locale];
  const kind=["observation","theory","crew"].includes(query.kind||"")?query.kind:undefined;
  const client=await authClient();let user=null;let posts:Post[]=[];let connected=false;let isPro=false;
  if(client)try{const auth=await client.auth.getUser();if(!auth.error&&auth.data.user?.email_confirmed_at)user=auth.data.user;if(user){const ent=await client.from("subscriptions").select("provider,status,current_period_end").eq("user_id",user.id).maybeSingle();isPro=!ent.error&&hasActiveSubscription(ent.data);}let builder=client.from("community_posts").select("id,author_name,kind,title,body,source_url,source_time,platform,language,spoiler,created_at,community_votes(count)").eq("status","published").order("created_at",{ascending:false}).limit(30);if(kind)builder=builder.eq("kind",kind);const result=await builder;if(!result.error){posts=result.data as Post[];connected=true;}}catch{}
  return <div className="community-page"><header><Link href="/"><ArrowLeft size={15}/>{t.home}</Link><span>VI COMPANION / AFTER DARK</span><nav><Link href="/guide">GUIDE</Link><Link href="/pricing">PRO</Link><div className="community-languages" aria-label="Language"><Link aria-current={locale==="en"?"page":undefined} href="/community?lang=en">EN</Link><Link aria-current={locale==="es"?"page":undefined} href="/community?lang=es">ES</Link><Link aria-current={locale==="pt-BR"?"page":undefined} href="/community?lang=pt-BR">PT</Link></div></nav></header><main><section className="community-hero"><span className="merged-kicker">{t.eyebrow}</span><h1>{t.title}</h1><p>{t.intro}</p><span className="community-trust"><ShieldCheck size={17}/>{t.warning}</span></section>
    <section id="board"><div className="community-filter" aria-label={t.filter}>{[["",t.all],["observation",t.observation],["theory",t.theory],["crew",t.crew]].map(([value,label])=><Link key={value} aria-current={(kind||"")===value?"page":undefined} href={`/community?lang=${locale}${value?`&kind=${value}`:""}#board`}>{label}</Link>)}</div>
      {!connected&&<p className="community-empty">{t.unavailable}</p>}{connected&&posts.length===0&&<p className="community-empty">{t.empty}</p>}
      <div className="community-posts">{posts.map(post=><article key={post.id}><div className="community-post-meta"><span>{t[post.kind]}</span><span>{post.spoiler?"⚠ SPOILER":post.language||""}</span><time dateTime={post.created_at}>{new Intl.DateTimeFormat(locale,{dateStyle:"medium"}).format(new Date(post.created_at))}</time></div>
        {post.spoiler?<><h2>⚠ SPOILER</h2><Link href={`/community/post/${post.id}?lang=${locale}`}>{t.showSpoiler}<ArrowUpRight size={15}/></Link></>:<><h2>{post.title}</h2><p>{post.body}</p>{post.source_url&&<a href={post.source_url} target="_blank" rel="nofollow noreferrer">{t.open}<ArrowUpRight size={15}/></a>}</>}
        <div className="community-post-footer"><span>{post.author_name} {post.platform&&post.platform!=="unspecified"?`· ${t.platforms[post.platform as keyof typeof t.platforms]||post.platform}`:""}</span>{user&&<div><form action={votePost}><input type="hidden" name="post_id" value={post.id}/><button type="submit">♡ {t.vote} {post.community_votes?.[0]?.count||0}</button></form><form action={reportPost}><input type="hidden" name="post_id" value={post.id}/><button type="submit">{t.report}</button></form></div>}</div>
      </article>)}</div></section>
    <section id="compose" className="community-compose"><span className="merged-kicker">{t.join}</span><h2>{t.submit}</h2><p>{t.rules}</p>{query.error&&<p role="alert" className="auth-error">{t.error}</p>}
      {connected&&user&&isPro?<form action={createPost}><div className="community-form-row"><label>{t.author}<input name="author_name" required minLength={2} maxLength={36}/></label><label>{t.language}<select name="language" defaultValue={locale}><option value="en">English</option><option value="es">Español</option><option value="pt-BR">Português (BR)</option></select></label></div><div className="community-form-row"><label>{t.filter}<select name="kind" defaultValue="observation"><option value="observation">{t.observation}</option><option value="theory">{t.theory}</option><option value="crew">{t.crew}</option></select></label><label>{t.platform}<select name="platform"><option value="unspecified">{t.platforms.unspecified}</option><option value="ps5">{t.platforms.ps5}</option><option value="xbox">{t.platforms.xbox}</option><option value="pc">{t.platforms.pc}</option></select></label></div><label>{t.postTitle}<input name="title" required minLength={8} maxLength={140}/></label><label>{t.body}<textarea name="body" required minLength={15} maxLength={2000} rows={6}/></label><div className="community-form-row"><label>{t.source}<input name="source_url" type="url" placeholder="https://" maxLength={500}/></label><label>{t.timestamp}<input name="source_time" type="number" min={0} max={7200}/></label></div><p className="source-hint">{t.sourceHint}</p><label className="spoiler-check"><input type="checkbox" name="spoiler"/>{t.spoiler}</label><button className="community-submit" type="submit">{t.publish}<ArrowUpRight size={16}/></button></form>:<div className="community-pro-lock"><LockKeyhole size={30}/><p>{connected?user?t.proLocked:t.signin:t.unavailable}</p>{connected&&<Link href={user?"/pricing":"/sign-in"}>{user?t.proPlans:t.signin}<ArrowUpRight size={15}/></Link>}</div>}
    </section></main></div>;
}
